services:
  consultants:
    image: debian:latest
    container_name: consultants
    hostname: consultants
    command: sleep infinity

  administrateurs:
    image: debian:latest
    container_name: administrateurs
    hostname: administrateurs
    command: sleep infinity

  DEBIAN-01:
    image: debian:latest
    container_name: DEBIAN-01
    hostname: DEBIAN-01
    command: sleep infinity